"""The spaces model and the Lua it generates.

A *page* is one keypress worth of desktop. Hyprland binds every workspace to
exactly one monitor, so a page that spans two screens is really a pair of
workspaces, one pinned per monitor:

    page N  ->  workspace N            on the first monitor
            ->  workspace N + offset   on the second
            ->  workspace N + 2*offset on a third, and so on

`offset` is what keeps the numbering unambiguous; with the default of 10 and
10 pages you get 1-10, 11-20, 21-30.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path


def config_dir() -> Path:
    """Resolved on every call, not at import, so tests and XDG both work."""
    return Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")


def state_path() -> Path:
    """Where the editor's own configuration lives."""
    return config_dir() / "hyprpages" / "pages.json"


def output_path(fmt: str = "lua") -> Path:
    """Where the generated config goes, per format."""
    return config_dir() / "hypr" / ("hyprpages.lua" if fmt == "lua" else "hyprpages.conf")


def detect_format() -> str:
    """Lua when the user has a Lua config, classic conf otherwise.

    Hyprland gained a Lua config in 0.55 and most setups have not moved to it,
    so guessing wrong here would generate a file the compositor cannot read.
    """
    return "lua" if (config_dir() / "hypr" / "hyprland.lua").exists() else "conf"


CONF_HEADER = """# Generated by hyprpages. Edits are overwritten on the next Apply.
#
# Load it from your hyprland.conf with:
#     source = ~/.config/hypr/hyprpages.conf
"""

GENERATED_HEADER = """-- Generated by hyprpages. Edits are overwritten on the next Apply.
--
-- Load it from your hyprland.lua with:
--     require("hypr.hyprpages")
--
-- Uses only Hyprland's own Lua API (hl.*), so it does not depend on any
-- distribution's config helpers.
"""


@dataclass
class App:
    """One window rule: a class pattern placed on a page and a monitor."""

    pattern: str  # Lua/Hyprland regex, e.g. ^google-chrome$
    page: int
    monitor: str  # monitor name, or "" for "wherever it opens"
    float: bool = False
    size: str = ""  # e.g. "1280 720"; only meaningful when float
    label: str = ""  # display name in the UI

    def workspace(self, cfg: PagesConfig) -> int | None:
        return cfg.workspace_for(self.page, self.monitor)


@dataclass
class PagesConfig:
    pages: int = 10
    offset: int = 10
    monitors: list[str] = field(default_factory=list)
    apps: list[App] = field(default_factory=list)
    pair_monitors: bool = True  # emit the workspace.active hook

    # ------------------------------------------------------------------ maths

    def workspace_for(self, page: int, monitor: str) -> int | None:
        if monitor not in self.monitors:
            return None
        if not 1 <= page <= self.pages:
            return None
        return page + self.offset * self.monitors.index(monitor)

    def page_of(self, workspace: int) -> tuple[int, str] | None:
        for index, monitor in enumerate(self.monitors):
            page = workspace - self.offset * index
            if 1 <= page <= self.pages:
                return page, monitor
        return None

    # ------------------------------------------------------------- persistence

    @classmethod
    def from_dict(cls, raw: dict) -> PagesConfig:
        """Build from untrusted JSON, ignoring keys we do not know.

        The editor is the only caller today, but tolerating unknown keys means
        an older binary will not crash on a config written by a newer one.
        """
        known = {f for f in cls.__dataclass_fields__ if f != "apps"}
        fields = {k: v for k, v in raw.items() if k in known}
        app_fields = set(App.__dataclass_fields__)
        apps = [
            App(**{k: v for k, v in app.items() if k in app_fields}) for app in raw.get("apps", [])
        ]
        return cls(apps=apps, **fields)

    @classmethod
    def load(cls) -> PagesConfig:
        path = state_path()
        if not path.exists():
            return cls()
        return cls.from_dict(json.loads(path.read_text()))

    def save(self) -> None:
        path = state_path()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(asdict(self), indent=2) + "\n")

    # ---------------------------------------------------------------- codegen

    def render(self, fmt: str) -> str:
        return self.to_lua() if fmt == "lua" else self.to_conf()

    def to_conf(self) -> str:
        """Classic hyprland.conf syntax.

        The Lua output can hook `workspace.active` to keep every screen on the
        same page however the switch was made. There is no equivalent in the
        conf format, so pages are bound to keys instead and the difference is
        stated in the file rather than left for the user to discover.
        """
        out = [CONF_HEADER]

        if not self.monitors:
            out.append("# No monitors configured yet.")
            return "\n".join(out) + "\n"

        out.append("# Pin each page's workspaces to their monitor.")
        for index, monitor in enumerate(self.monitors):
            for page in range(1, self.pages + 1):
                out.append(f"workspace = {page + self.offset * index}, monitor:{monitor}")
        out.append("")

        if self.apps:
            out.append("# Window placement.")
            for app in self.apps:
                for rule in self._conf_rules(app):
                    out.append(f"windowrule = {rule}, class:{app.pattern}")
            out.append("")

        if self.pair_monitors and len(self.monitors) > 1:
            out.append(
                "# Switch every screen to the same page at once. The Lua config can do\n"
                "# this by hooking workspace.active, which also catches clicks on a bar\n"
                "# and SUPER+scroll; conf syntax has no events, so it is bound to keys."
            )
            for page in range(1, min(self.pages, 10) + 1):
                key = 0 if page == 10 else page
                out.append(f"bind = SUPER, {key}, exec, hyprpages page {page}")
            out.append("")

        return "\n".join(out) + "\n"

    def _conf_rules(self, app: App) -> list[str]:
        rules: list[str] = []
        ws = app.workspace(self)
        if ws is not None:
            rules.append(f"workspace {ws} silent")
        if app.float:
            rules.append("float")
            if app.size:
                rules.append(f"size {app.size}")
        return rules

    def to_lua(self) -> str:
        out = [GENERATED_HEADER]

        if len(self.monitors) < 1:
            out.append("-- No monitors configured yet.\n")
            return "\n".join(out)

        out.append("-- Pin each page's workspaces to their monitor.")
        out.append(f"for page = 1, {self.pages} do")
        for index, monitor in enumerate(self.monitors):
            expr = "page" if index == 0 else f"page + {self.offset * index}"
            out.append(
                f"  hl.workspace_rule({{ workspace = tostring({expr}), "
                f'monitor = "{_lua_escape(monitor)}" }})'
            )
        out.append("end\n")

        if self.apps:
            out.append("-- Window placement.")
        for app in self.apps:
            out.append(self._app_lua(app))
        if self.apps:
            out.append("")

        if self.pair_monitors and len(self.monitors) > 1:
            out.append(self._pairing_lua())

        return "\n".join(out)

    def _app_lua(self, app: App) -> str:
        rules: list[str] = []
        ws = app.workspace(self)
        if ws is not None:
            rules.append(f'workspace = "{ws} silent"')
        if app.float:
            rules.append("float = true")
            if app.size:
                rules.append(f'size = "{_lua_escape(app.size)}"')
        if not rules:
            return f"-- (no rules for {app.pattern})"
        comment = f"  -- {app.label}" if app.label else ""
        return (
            f'hl.window_rule({{ match = {{ class = "{_lua_escape(app.pattern)}" }}, '
            f"{', '.join(rules)} }}){comment}"
        )

    def _pairing_lua(self) -> str:
        """Keep every monitor on the same page, however the switch was made.

        Binding the number keys is not enough: the bar's Workspaces widget and
        SUPER+scroll both call hl.dsp.focus directly. Hooking the event catches
        every route. The re-entrancy flag is essential -- each focus issued
        here fires workspace.active again.
        """
        names = ", ".join(f'"{_lua_escape(m)}"' for m in self.monitors)
        return f"""-- Keep the screens on the same page, whatever triggered the switch.
local page_monitors = {{ {names} }}
local page_offset, page_count = {self.offset}, {self.pages}
local page_syncing = false

hl.on("workspace.active", function(ws)
  if page_syncing then
    return
  end
  local id = ws and ws.id
  local monitor = ws and ws.monitor and ws.monitor.name
  if type(id) ~= "number" or not monitor then
    return
  end

  local page, index
  for i, name in ipairs(page_monitors) do
    if name == monitor then
      index = i - 1
    end
  end
  if not index then
    return
  end
  page = id - page_offset * index
  if page < 1 or page > page_count then
    return -- special workspaces and anything unpinned are left alone
  end

  page_syncing = true
  for i, name in ipairs(page_monitors) do
    if name ~= monitor then
      hl.dispatch(hl.dsp.focus({{ monitor = name }}))
      hl.dispatch(hl.dsp.focus({{ workspace = tostring(page + page_offset * (i - 1)) }}))
    end
  end
  hl.dispatch(hl.dsp.focus({{ monitor = monitor }}))
  page_syncing = false
end)
"""


def _lua_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def class_to_pattern(cls: str) -> str:
    """Anchor a window class into a rule pattern, escaping regex metacharacters."""
    return "^" + re.sub(r"([.^$*+?()\[\]{}|\\])", r"\\\1", cls) + "$"
